name: API Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Run TestNG Tests
        run: mvn clean test -DsuiteXmlFile=testng.xml
        working-directory: ./Test

      - name: Zip TestNG Report
        run: zip -r test-report.zip Test/test-output
        working-directory: ./Test

      - name: Send Test Report via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "OMNI - TestNG API Automation Report"
          to: ayesha.ghaffar@m3tech.com.pk
          from: ${{ secrets.EMAIL_USERNAME }}
          content_type: text/html
          body: |
            <p>Hi,</p>
            <p>Here is the latest TestNG API Automation report of OMNI Product.</p>
            <p>Regards,<br>M3Tech SQA Team</p>
          attachments: ./Test/test-report.zip
