name: API Test Automation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run API Tests using TestNG
        working-directory: ./Test
        run:  mvn clean test

      - name: List test output files (for debugging)
        working-directory: ./Test
        run: ls -R

      - name: Zip test-output directory
        if: success()
        working-directory: ./Test
        run: |
          if [ -d "test-output" ]; then
            zip -r test-report.zip test-output
          else
            echo "❌ test-output directory not found"
            exit 1
          fi

      - name: Upload test report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: Test/test-report.zip

# === Optional Email (commented out) ===
# Uncomment below if email sending is required in future

#      - name: Rename zip to .txt (to avoid Gmail block)
#        run: mv Test/test-report.zip Test/test-report.txt

#      - name: Send Test Report via Email
#        uses: dawidd6/action-send-mail@v3
#        with:
#          server_address: smtp.gmail.com
#          server_port: 465
#          secure: true
#          username: ${{ secrets.EMAIL_USERNAME }}
#          password: ${{ secrets.EMAIL_PASSWORD }}
#          subject: "OMNI - TestNG API Automation Report"
#          to: ayesha.ghaffar@m3tech.com.pk
#          from: ${{ secrets.EMAIL_USERNAME }}
#          body: |
#            <p>Hi,</p>
#            <p>Here is the latest TestNG API Automation report of OMNI Product.</p>
#            <p>Regards,<br>M3Tech SQA Team</p>
#          attachments: Test/test-report.txt
